lang: pt-br
title: COVID-19 Animated Bar Chart Race
description: Gráficos e animações sobre a evolução da COVID-19 no Brasil e no Mundo
show_downloads: false
theme: jekyll-theme-cayman
root: /
baseurl: /
url: http://bgeneto.github.io
github:
  is_project_page: true
  repository_url: https://github.com/bgeneto/covid-19
  repository_name: covid-19
  owner_url: https://github.com/bgeneto
  owner_name: bgeneto
